### ISSUE TITLE
同意请求报错

### ISSUE THREAD

**Issue by FantasyOwl** [PadorFelice/nonebot_plugin_eventdone#2]
罐头出错了
错误信息：invalid literal for int() with base 10: ''

**Comment by PadorFelice** [comment]
是在什么情况下发生的？

**Comment by PadorFelice** [comment]
如果是一个好友重复同意之后删除的话确实可能会出现这个错误（是我最近比较忙没时间去修这个bug）

**Comment by FantasyOwl** [comment]
> 是在什么情况下发生的？

我用一个QQ号去申请加机器人，然后机器人返回消息给超级管理员的QQ，我用超级管理员的QQ回复“同意”，然后机器人返回这个报错

**Comment by FantasyOwl** [comment]
> 如果是一个好友重复同意之后删除的话确实可能会出现这个错误（是我最近比较忙没时间去修这个bug）

没有，就是第一次加，
![image](https://user-images.githubusercontent.com/86191035/195869532-2d7960f3-ae18-42d8-828f-d5a47f1e1e8b.png)
